### ISSUE TITLE
Bug on yesterday matches

### ISSUE THREAD

**Issue by gmmcal** [sportdb/footty#1]
I think there’s an issue on this line https://github.com/sportdb/footty/blob/master/lib/footty.rb#L42

Instead of calling `get_todays_matches`, it should call `get_yesterdays_matches`.

I can’t confirm now or send a PR because I’m far from my computer, but I can try tomorrow if the bug is confirmed and still persists

**Comment by geraldb** [comment]
@gmmcal  Wow. Thanks for looking at the code. You're right. Didn't notice - still 4 days to kick off (thus, no yesterdays matches).  Changed the code according to your suggestions. Thanks. Keep it up. Cheers. Prost. Enjoy the beautiful game.
